
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-11
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-11
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-email-form-component","number":30,"title":"ws - role email form component","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/30"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-instructor-tables","number":29,"title":"ws - added instructor table files","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/29"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"create-admin-table","number":28,"title":"sl - create Admin table","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/28"}]
