
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-11
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-11
pull_requests: [{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-CourseStaffExtraImplementations","number":43,"title":"js - course staff extra implementations","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/43"},{"author":{"id":"MDQ6VXNlcjUzMjM2OTYx","is_bot":false,"login":"Wendy192837","name":""},"headRefName":"ws-roster-students-form-component","number":42,"title":"ws - roster students form component and fixtures","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/42"},{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-Instructors-delete","number":41,"title":"lm - instructors delete ","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/41"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-StaffLookUpCourses","number":40,"title":"js - added backend end point student staff to look up what course they are on ","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/40"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-initialize-admins-table-on-startup","number":37,"title":"tr - added startup code to populate Admins table from ADMIN_EMAILS","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/37"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-RosterStudent-add-delete-method","number":36,"title":"tr - add delete method for RosterStudent controller","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/36"},{"author":{"id":"U_kgDOB2-2PA","is_bot":false,"login":"Sauld04","name":"Saul Diaz "},"headRefName":"sd-admin-controller-delete","number":35,"title":"sd - Admin DELETE operation implemented ","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/35"}]
