
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-11
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-11
pull_requests: [{"author":{"id":"U_kgDOCRaVBA","is_bot":false,"login":"luismendoza25","name":"Luis Mendoza"},"headRefName":"lm-Instructors-createAndReturn","number":39,"title":"POST and GET for Instructors Table","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/39"},{"author":{"id":"U_kgDOB5HCgg","is_bot":false,"login":"aaasami","name":"Shuang"},"headRefName":"sl-add-RosterStudent-table-component","number":38,"title":"sl - add table component for RosterStudents(storybook only)","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/38"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-initialize-admins-table-on-startup","number":37,"title":"tr - added startup code to populate Admins table from ADMIN_EMAILS","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/37"},{"author":{"id":"U_kgDOB3DvIw","is_bot":false,"login":"Trocha1","name":""},"headRefName":"tr-RosterStudent-add-delete-method","number":36,"title":"tr - add delete method for RosterStudent controller","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/36"},{"author":{"id":"U_kgDOB2-2PA","is_bot":false,"login":"Sauld04","name":"Saul Diaz "},"headRefName":"sd-admin-controller-delete","number":35,"title":"sd - Admin DELETE operation implemented ","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/35"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-StudentLookUpCourses","number":34,"title":"js - added backend method for students to see courses they appear on roster of and status","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/34"}]
