
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-11
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-11
pull_requests: [{"author":{"id":"U_kgDOB2-2PA","is_bot":false,"login":"Sauld04","name":"Saul Diaz "},"headRefName":"sd-admin-controller-delete","number":35,"title":"sd - Admin DELETE operation implemented ","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/35"},{"author":{"id":"U_kgDOCM7m9w","is_bot":false,"login":"jonahso","name":""},"headRefName":"js-StudentLookUpCourses","number":34,"title":"js - added backend method for students to see courses they appear on roster of and status","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-11/pull/34"}]
